### ISSUE TITLE
[Request] Deployment Example

### ISSUE THREAD

**Issue by elzii** [Alex-ray/universal-hmr-ssr-react-redux#3]
Being naive and working with zero-configs that spit out an `index.html` already including production assets, etc in build... How would I go about deploying this after building?

Cheers

**Comment by Alex-ray** [comment]
Hey @elzii , I actually just re-launched my personally website using this same general configuration which you can view over here https://github.com/Alex-ray/alexjray.com.

Essentially I uploaded all the static assets to Amazon s3 via a [simple gulp script](https://github.com/Alex-ray/alexjray.com/blob/master/Gulpfile.js), I then [replaced the static output path in the webpack config](https://github.com/Alex-ray/alexjray.com/blob/master/webpack/webpack.config.prod.js#L57) with my amazon bucket url.

I then used digital ocean to create a [Dokku](https://github.com/dokku/dokku) instance, added a [Procfile](https://github.com/Alex-ray/alexjray.com/blob/master/Procfile) and used a heroku like deploy setup. `git push production master` and boom you have node.js rendering all your routes on the server with all your assets hosted on amazon S3 😀

I am looking to write a bit more about all this and will get a medium post up soon so [stay tuned](https://medium.com/@_alexray) and let me know if you have any troubles!

**Comment by elzii** [comment]
Thanks so much for taking time to respond. Super helpful and got me past something that was roadblocking me. Days like this I love GitHub... can't wait to give back.

**Comment by Alex-ray** [comment]
No problem @elzii , glad you got things up and running!

Definitely let me know if you have any more questions
