### ISSUE TITLE
Reason for having 2 webpacks - client and server

### ISSUE THREAD

**Issue by splendidtrade** [Alex-ray/universal-hmr-ssr-react-redux#4]
@Alex-ray Would you mind telling the reason why did you have 2 webpacks(server and client) and for server side rendering I thought the starting point will be server.js - but I see it is client.js under clients folder - does this achieve server side rendering - I am planning to use your project as a boiler plate set up for my server side rendering app - but not quite following the flow - could you please add little description. Thanks in advance.

**Comment by Alex-ray** [comment]
Hey @splendidtrade , no problem!

I assume your referencing the three different webpack configurations?

Let me clarify each of their purposes.

1. The first one  `webpack.config.prod.js`  is for the client side code(the code that is requested via the browser, aka `app.js`), this is your production client side react application.

2. there is also a development configuration `webpack.config.dev.js` which is for hot module reloading when in development mode and is used on the server via an express webpack middleware. When in development mode you load client side code that communicates with the webpack middleware and automagically updates your react components.

3. The last configuration, and the one I think your referencing is the `webpack.config.server.js` configuration; This one is used to build a bundle that we can use to match requests with your react router routes on the server. This is so we can throw not found errors and things like that. For this use case we only need to build the `router/index.js` bundle which is what were doing here https://github.com/Alex-ray/universal-hmr-ssr-react-redux/blob/master/webpack/webpack.config.server.js#L17

The entry point `client.js` that you mention is the entry point to the javascript application itself and is the script that is sent to the browser and run to render your react application...

On that same note I do have a newer updated project over here, I do recommend you use that. https://github.com/Alex-ray/v2-universal-js-hmr-ssr-react-redux

If you follow the trail from `package.json` commands to the correlating files and imports  you can easily find your way through the whole app; its a great way to learn a codebase but does take a bit of concentration 😉 

I hope this helps and please reach out if you need some further clarification on anything!

**Comment by splendidtrade** [comment]
@Alex-ray Sure. Thanks for your reply - I was also going through your video walk through - I am stumbled up on seeing 2 server.babel.js files one under src/server and one under webpack? and packages.json dev script starts file under server and build script under webpack? why is that ? also in your video you have opened the file under webpack? is that the right one? could you please clarify..

**Comment by splendidtrade** [comment]
@Alex-ray Thanks for your reply - yes I watched your video walk through and I am pretty clear now - how it works. I have couple more questions - 
1) when I run npm build and npm start prod set up I am getting 
**ReferenceError: self is not defined
    at ../build/prerender.js:32:2098**
is it because of the css/sass loaders I have? This is my loader configuration - I basically have 1 main.scss and include rest of the component specific css within this file - 
 { test: /\.(png|jpg|jpeg|gif|svg)$/, loader: 'url-loader?name=img/img-[hash:6].[ext]&limit=5000' },
    {
                test: /\.scss/,
                loader: [
                    'style-loader',
                    {
                        loader: 'css-loader',
                        options: {
                            sourceMap: true,
                            url: false
                        }
                    },
                    {
                        loader: 'sass-loader',
                        options: {
                            sourceMap: true,
                            url: false
                        }
                    }
                ]
            },

2) ****const makeRoutes = require('../../build/prerender');**
const routes = makeRoutes(store);**
why do we need to take it as a bundle here - can we not pass directly 1 route file?

3) And last question - which is the right place to make a call to external API and how do I pass in the data coming back into appropriate components? can I take counter.js actions as an example? but I dont see we are injecting actual data from server anywhere. Could you please give me some direction here.
